name: duaya_app
description: "A new duaya app."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
#-------------------- PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Utility Package
  intl: ^0.18.1
  webview_flutter: ^2.0.13
  webview_flutter_wkwebview:
  flutter_native_splash: ^2.3.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  url_launcher:
  image_picker: ^1.0.7
  floating_snackbar: ^1.0.3+1
  data_connection_checker_tv:
  iconsax: ^0.0.8
  # State Management
  flutter_bloc: ^8.1.3
  # Connect to api
  dio: ^5.4.1
  # Product Specific
  cached_network_image: ^3.3.0
  # Responsive Ui
  flutter_screenutil: ^5.9.0
  # Make Animation When Navigate
  page_transition: ^2.1.0
  # SVG Pictures
  flutter_svg: ^2.0.9
  # Custom Field On OTP
  pinput: ^3.0.1
  fluttertoast: ^8.0.8


  # voice assestant
  flutter_tts: ^3.3.2 # Check for the latest version

  # Check to Internet
  internet_connection_checker: ^1.0.0+1

  # Get Location => Map Services
#  geolocator: any
  geocoding: null
  google_maps_flutter:
  maps_launcher: ^2.2.0

#-------------------- PACKAGES End --------------------#
dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "flutter_luancher"
  ios: true
#  image_path: "assets/images/pngs/app-logo.png"
  image_path: "assets/animations/logoAnimation.gif"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/lotties/
    - assets/animations/
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/images/jpegs/
    - assets/images/pngs/social_images/
    - assets/images/GIF/
    - assets/images/pngs/on_boarding_images/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ar/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Cairo-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/en/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/en/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/en/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/en/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/en/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/en/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/en/Poppins-Bold.ttf
          weight: 800

#    - family: Playfair Display
#      fonts:
#        - asset: fonts/PlayfairDisplay-Regular.ttf
#        - asset: fonts/PlayfairDisplay-Bold.ttf
#          weight: 700
flutter_intl:
  enabled: true
